export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SET_PROD_Searchbarhold:"SET_PROD_Searchbarhold",
   SET_PRODUCTCART:"SET_PRODUCTCART",
  
   SET_WISHLIST:"SET_WISHLIST",
   SET_DEPARTMENT:"SET_DEPARTMENT",
   SET_REVIEW:"SET_REVIEW",
   SET_ELECTRONICS:"SET_ELECTRONICS",
 
}